"""Immutable registry for every PNG generated by BroEdenBot.

The dashboard and renderer integration both consume these definitions. Upload
recommendations must never be duplicated in templates or JavaScript.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from fractions import Fraction
from typing import Any, Dict, Iterable, Mapping, Optional, Tuple


SUPPORTED_IMAGE_FORMATS = ("PNG", "JPEG", "WEBP")
MAX_UPLOAD_BYTES = 10_000_000


@dataclass(frozen=True)
class SafeArea:
    top: int
    right: int
    bottom: int
    left: int
    obscured_regions: Tuple[Tuple[int, int, int, int, str], ...] = ()


@dataclass(frozen=True)
class AssetSlot:
    key: str
    label: str
    asset_type: str
    recommended_width: int
    recommended_height: int
    minimum_width: int
    minimum_height: int
    maximum_width: int
    maximum_height: int
    maximum_bytes: int = MAX_UPLOAD_BYTES
    formats: Tuple[str, ...] = SUPPORTED_IMAGE_FORMATS
    transparency: str = "supported"
    fit: str = "cover"
    safe_area: SafeArea = field(default_factory=lambda: SafeArea(0, 0, 0, 0))
    description: str = ""

    @property
    def aspect_ratio(self) -> str:
        fraction = Fraction(
            self.recommended_width, self.recommended_height
        ).limit_denominator(512)
        return "{}:{}".format(fraction.numerator, fraction.denominator)

    def as_dict(self) -> Dict[str, Any]:
        value = asdict(self)
        value["aspect_ratio"] = self.aspect_ratio
        value["formats"] = list(self.formats)
        value["safe_area"]["obscured_regions"] = [
            {
                "x": region[0],
                "y": region[1],
                "width": region[2],
                "height": region[3],
                "label": region[4],
            }
            for region in self.safe_area.obscured_regions
        ]
        return value


@dataclass(frozen=True)
class TemplateDefinition:
    key: str
    display_name: str
    description: str
    category: str
    renderer: str
    width: int
    height: int
    supported_settings: Tuple[str, ...]
    asset_slots: Tuple[AssetSlot, ...]
    defaults: Mapping[str, Any]
    command_source: str
    maximum_items: int = 0
    output_format: str = "PNG"
    max_output_bytes: int = 8_000_000
    legacy_fallback: str = ""

    @property
    def aspect_ratio(self) -> str:
        fraction = Fraction(self.width, self.height).limit_denominator(512)
        return "{}:{}".format(fraction.numerator, fraction.denominator)

    def slot(self, key: str) -> AssetSlot:
        for slot in self.asset_slots:
            if slot.key == key:
                return slot
        raise KeyError("Unknown asset slot {!r} for {}".format(key, self.key))

    def as_dict(self) -> Dict[str, Any]:
        return {
            "template_key": self.key,
            "display_name": self.display_name,
            "description": self.description,
            "category": self.category,
            "renderer": self.renderer,
            "canvas": {"width": self.width, "height": self.height},
            "aspect_ratio": self.aspect_ratio,
            "output": {
                "format": self.output_format,
                "max_file_size_bytes": self.max_output_bytes,
            },
            "supported_settings": list(self.supported_settings),
            "asset_slots": [slot.as_dict() for slot in self.asset_slots],
            "defaults": dict(self.defaults),
            "command_source": self.command_source,
            "maximum_items": self.maximum_items,
            "legacy_fallback": self.legacy_fallback,
        }


class TemplateRegistry:
    def __init__(self, templates: Iterable[TemplateDefinition] = ()) -> None:
        self._templates: Dict[str, TemplateDefinition] = {}
        for template in templates:
            self.register(template)

    def register(self, template: TemplateDefinition) -> None:
        if not template.key or not template.key.replace("_", "").isalnum():
            raise ValueError("Template keys must contain letters, digits, and underscores.")
        if template.key in self._templates:
            raise ValueError("Duplicate visual template key: {}".format(template.key))
        if template.width <= 0 or template.height <= 0:
            raise ValueError("Template canvas dimensions must be positive.")
        slot_keys = [slot.key for slot in template.asset_slots]
        if len(slot_keys) != len(set(slot_keys)):
            raise ValueError("Duplicate asset slot in {}".format(template.key))
        self._templates[template.key] = template

    def get(self, key: str) -> TemplateDefinition:
        try:
            return self._templates[key]
        except KeyError:
            raise KeyError("Unknown visual template: {}".format(key))

    def all(self) -> Tuple[TemplateDefinition, ...]:
        return tuple(
            sorted(
                self._templates.values(),
                key=lambda item: (item.category, item.display_name.casefold()),
            )
        )

    def as_dicts(self) -> Tuple[Dict[str, Any], ...]:
        return tuple(template.as_dict() for template in self.all())


RANKED_SETTINGS = (
    "background",
    "header_graphic",
    "theme",
    "logo",
    "watermark",
    "title",
    "subtitle",
    "footer_text",
    "accent_color",
    "panel_color",
    "panel_opacity",
    "text_color",
    "muted_text_color",
    "secondary_color",
    "title_color",
    "body_text_color",
    "border_color",
    "divider_color",
    "shadow_strength",
    "gradient",
    "title_font",
    "body_font",
    "title_size",
    "subtitle_size",
    "body_size",
    "footer_size",
    "border_radius",
    "first_place_color",
    "second_place_color",
    "third_place_color",
    "footer_styling",
    "density",
    "avatar_shape",
    "show_avatars",
    "show_ranks",
    "show_timestamp",
    "maximum_rows",
    "background_fit",
    "focal_x",
    "focal_y",
    "background_brightness",
    "background_blur",
    "background_saturation",
    "background_contrast",
    "background_overlay",
    "background_overlay_opacity",
    "high_contrast",
    "reduced_decoration",
)

WIDE_SETTINGS = tuple(
    key
    for key in RANKED_SETTINGS
    if key not in {"density", "avatar_shape", "show_avatars", "maximum_rows"}
)

DEFAULTS = {
    "accent_color": "#f0319b",
    "panel_color": "#171820",
    "panel_opacity": 1.0,
    "text_color": "#f4f4f7",
    "muted_text_color": "#a7a8b3",
    "border_color": "#30313d",
    "title_font": "Open Sans Emoji",
    "body_font": "Open Sans Emoji",
    "density": "balanced",
    "avatar_shape": "circle",
    "show_avatars": True,
    "show_ranks": True,
    "show_timestamp": True,
    "background_fit": "cover",
    "focal_x": 0.5,
    "focal_y": 0.5,
    "background_brightness": 1.0,
    "background_blur": 0.0,
    "background_saturation": 1.0,
    "background_contrast": 1.0,
    "background_overlay": "#0c0d12",
    "background_overlay_opacity": 0.56,
    "high_contrast": False,
    "reduced_decoration": False,
}


def _background_slot(width: int, height: int, safe: SafeArea) -> AssetSlot:
    return AssetSlot(
        key="background",
        label="Full-canvas background",
        asset_type="background",
        recommended_width=width,
        recommended_height=height,
        minimum_width=max(1, int(width * 0.8)),
        minimum_height=max(1, int(height * 0.8)),
        maximum_width=width * 3,
        maximum_height=height * 3,
        safe_area=safe,
        fit="cover",
        description="The normalized copy is cropped to cover the full canvas.",
    )


PORTRAIT_SAFE = SafeArea(
    48,
    48,
    70,
    48,
    (
        (48, 48, 1104, 208, "Header and title"),
        (48, 286, 1104, 1144, "Leaderboard content panel"),
        (48, 1444, 1104, 28, "Footer"),
    ),
)
WIDE_SAFE = SafeArea(
    48,
    48,
    70,
    48,
    (
        (48, 48, 1504, 208, "Header and title"),
        (48, 286, 1504, 502, "Report content"),
        (48, 844, 1504, 28, "Footer"),
    ),
)
QUEUE_SAFE = SafeArea(
    36,
    36,
    36,
    36,
    (
        (90, 118, 520, 90, "Member display name"),
        (650, 28, 202, 202, "Member avatar"),
    ),
)

HEADER_SLOT = AssetSlot(
    key="header_graphic",
    label="Header graphic",
    asset_type="header_graphic",
    recommended_width=1104,
    recommended_height=208,
    minimum_width=552,
    minimum_height=104,
    maximum_width=3312,
    maximum_height=624,
    safe_area=SafeArea(24, 24, 24, 24),
    fit="cover",
    description="Displayed inside the rounded title header.",
)

LOGO_SLOT = AssetSlot(
    key="logo",
    label="Server logo",
    asset_type="logo",
    recommended_width=1024,
    recommended_height=1024,
    minimum_width=256,
    minimum_height=256,
    maximum_width=2048,
    maximum_height=2048,
    formats=("PNG", "WEBP"),
    transparency="recommended",
    fit="contain",
    safe_area=SafeArea(32, 32, 32, 32),
    description="Contained without distortion; transparent padding is preserved.",
)

WATERMARK_SLOT = AssetSlot(
    key="watermark",
    label="Watermark",
    asset_type="watermark",
    recommended_width=1200,
    recommended_height=300,
    minimum_width=600,
    minimum_height=150,
    maximum_width=2400,
    maximum_height=600,
    formats=("PNG", "WEBP"),
    transparency="recommended",
    fit="contain",
    safe_area=SafeArea(20, 20, 20, 20),
    description="Transparent wide mark placed within the renderer footer treatment.",
)


def _ranked(
    key: str,
    name: str,
    description: str,
    category: str,
    command: str,
    legacy: str = "",
) -> TemplateDefinition:
    defaults = dict(DEFAULTS)
    defaults["maximum_rows"] = 10
    return TemplateDefinition(
        key=key,
        display_name=name,
        description=description,
        category=category,
        renderer="utils.stats_visuals.render_ranked_graphic_result",
        width=1200,
        height=1500,
        supported_settings=RANKED_SETTINGS,
        asset_slots=(
            _background_slot(1200, 1500, PORTRAIT_SAFE),
            HEADER_SLOT,
            LOGO_SLOT,
            WATERMARK_SLOT,
        ),
        defaults=defaults,
        command_source=command,
        maximum_items=10,
        legacy_fallback=legacy,
    )


_TEMPLATES = (
    _ranked(
        "activity_leaderboard",
        "Activity Leaderboard",
        "Ranked message or voice activity generated by Stats Graphics.",
        "analytics",
        "/stats activity and tracked activity reports",
    ),
    _ranked(
        "vc_leaderboard",
        "Voice Leaderboard",
        "Ranks members by tracked voice-channel time.",
        "leaderboards",
        "/vcstats leaderboard",
    ),
    _ranked(
        "custom_leaderboard",
        "Custom Leaderboard",
        "Staff-managed points leaderboard with optional legacy banner.",
        "leaderboards",
        "/leaderboard and leaderboard buttons",
        "Legacy leaderboard banner BLOB remains available.",
    ),
    _ranked(
        "bump_leaderboard",
        "Bump Legends Leaderboard",
        "Ranks verified DISBOARD bump contributions.",
        "leaderboards",
        "!bumpscores and the managed bump post",
        "assets/bump_leaderboard_background[.png]",
    ),
    _ranked(
        "streak_leaderboard",
        "Activity Streak Leaderboard",
        "Current, longest, and weekly member activity streaks.",
        "leaderboards",
        "/streak leaderboard and weekly streak post",
        "assets/streak_leaderboard_background.png",
    ),
    TemplateDefinition(
        key="role_roster",
        display_name="Role Roster",
        description="Paginated member roster for a tracked Discord role.",
        category="statistics",
        renderer="utils.stats_visuals.render_compact_roster_result",
        width=1200,
        height=1500,
        supported_settings=RANKED_SETTINGS,
        asset_slots=(
            _background_slot(1200, 1500, PORTRAIT_SAFE),
            HEADER_SLOT,
            LOGO_SLOT,
            WATERMARK_SLOT,
        ),
        defaults={**DEFAULTS, "maximum_rows": 12},
        command_source="tracked role statistics graphics",
        maximum_items=12,
        legacy_fallback="role_stat_embeds.image_data banner BLOB",
    ),
    *(
        TemplateDefinition(
            key=key,
            display_name=name,
            description=description,
            category="statistics",
            renderer=renderer,
            width=1600,
            height=900,
            supported_settings=WIDE_SETTINGS,
            asset_slots=(
                _background_slot(1600, 900, WIDE_SAFE),
                LOGO_SLOT,
                WATERMARK_SLOT,
            ),
            defaults={
                key: value for key, value in DEFAULTS.items() if key in WIDE_SETTINGS
            },
            command_source=command,
            legacy_fallback="Built-in Pillow renderer",
        )
        for key, name, description, renderer, command in (
            (
                "role_comparison",
                "Role Comparison",
                "Compares membership across two roles.",
                "utils.stats_visuals.render_rolecompare_result",
                "/stats rolecompare and tracked reports",
            ),
            (
                "missing_role",
                "Missing Role Coverage",
                "Shows required-role coverage and missing membership.",
                "utils.stats_visuals.render_missingrole_result",
                "/stats missingrole and tracked reports",
            ),
            (
                "stats_error",
                "Stats Error Card",
                "Safe visual fallback for a tracked report failure.",
                "utils.stats_visuals.render_error_result",
                "automatic tracked-report fallback",
            ),
        )
    ),
    TemplateDefinition(
        key="queue_next",
        display_name="Queue Up Next Banner",
        description="Highlights the next member in a voice-channel queue.",
        category="events",
        renderer="cogs.queue.Queue.create_banner",
        width=1024,
        height=258,
        supported_settings=(
            "background",
            "theme",
            "accent_color",
            "text_color",
            "title_font",
            "body_size",
            "background_fit",
            "focal_x",
            "focal_y",
        ),
        asset_slots=(
            AssetSlot(
                key="background",
                label="Queue banner base image",
                asset_type="background",
                recommended_width=1024,
                recommended_height=258,
                minimum_width=1024,
                minimum_height=258,
                maximum_width=3072,
                maximum_height=774,
                safe_area=QUEUE_SAFE,
                fit="cover",
                description="The name and avatar are composited over this base.",
            ),
        ),
        defaults={
            "accent_color": "#f0319b",
            "text_color": "#ffffff",
            "background_fit": "cover",
            "focal_x": 0.5,
            "focal_y": 0.5,
            "body_size": 40,
        },
        command_source="/queue dashboard and queue controls",
        maximum_items=1,
        legacy_fallback="assets/up_next.png",
    ),
)


REGISTRY = TemplateRegistry(_TEMPLATES)


def template_registry() -> TemplateRegistry:
    return REGISTRY


def asset_type_guidance(asset_type: str) -> Dict[str, Any]:
    """Return generic guidance when an asset is not tied to a template slot."""
    definitions = {
        "logo": (1024, 1024, 256, 256, 2048, 2048, "1:1", "required"),
        "watermark": (1200, 300, 600, 150, 2400, 600, "4:1", "required"),
        "header_graphic": (1104, 208, 552, 104, 3312, 624, "69:13", "supported"),
        "overlay": (1600, 900, 320, 180, 4800, 2700, "varies", "required"),
        "avatar_frame": (512, 512, 256, 256, 1024, 1024, "1:1", "required"),
        "badge": (256, 256, 64, 64, 1024, 1024, "1:1", "required"),
        "icon": (256, 256, 64, 64, 1024, 1024, "1:1", "required"),
    }
    values = definitions.get(asset_type, (1600, 900, 320, 180, 4800, 2700, "varies", "supported"))
    return {
        "recommended_width": values[0],
        "recommended_height": values[1],
        "minimum_width": values[2],
        "minimum_height": values[3],
        "maximum_width": values[4],
        "maximum_height": values[5],
        "aspect_ratio": values[6],
        "transparency": values[7],
        "maximum_bytes": MAX_UPLOAD_BYTES,
        "formats": list(
            ("PNG", "WEBP") if values[7] == "required" else SUPPORTED_IMAGE_FORMATS
        ),
    }
