#!/usr/bin/env python3
"""Generate the Visual Content Studio upload-size Markdown from the registry."""

from pathlib import Path
import sys

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT))
from utils.visual_studio.registry import REGISTRY, asset_type_guidance
from utils.visual_studio.storage import ASSET_TYPES


OUTPUT = PROJECT_ROOT / "docs" / "visual-content-studio-size-reference.md"


def document() -> str:
    lines = [
        "# Visual Content Studio upload-size reference",
        "",
        "<!-- Generated by scripts/generate_visual_size_reference.py. Do not edit by hand. -->",
        "",
        "The dashboard reads these same values directly from the registry.",
        "",
        "| Template | Asset slot | Recommended | Ratio | Minimum | Maximum | Max file | Formats | Alpha | Safe area T/R/B/L | Fit |",
        "|---|---|---:|---:|---:|---:|---:|---|---|---:|---|",
    ]
    for definition in REGISTRY.all():
        for slot in definition.asset_slots:
            lines.append(
                "| {name} | {slot} | {rw}x{rh} | {ratio} | {minw}x{minh} | {maxw}x{maxh} | {mb} MB | {formats} | {alpha} | {top}/{right}/{bottom}/{left} | {fit} |".format(
                    name=definition.display_name,
                    slot=slot.label,
                    rw=slot.recommended_width,
                    rh=slot.recommended_height,
                    ratio=slot.aspect_ratio,
                    minw=slot.minimum_width,
                    minh=slot.minimum_height,
                    maxw=slot.maximum_width,
                    maxh=slot.maximum_height,
                    mb=slot.maximum_bytes // 1_000_000,
                    formats=", ".join(slot.formats),
                    alpha=slot.transparency,
                    top=slot.safe_area.top,
                    right=slot.safe_area.right,
                    bottom=slot.safe_area.bottom,
                    left=slot.safe_area.left,
                    fit=slot.fit,
                )
            )
    lines.extend(
        [
            "",
            "Background recommendations match the final renderer canvas. Header recommendations match the exact header destination rectangle. Larger same-ratio images are normalized once during upload.",
            "",
            "## Generic Asset Library uploads",
            "",
            "Use template-specific guidance whenever the asset has a known destination. These values apply when uploading a reusable asset without selecting a template slot.",
            "",
            "| Asset type | Recommended | Ratio | Minimum | Maximum | Max file | Formats | Alpha |",
            "|---|---:|---:|---:|---:|---:|---|---|",
        ]
    )
    for asset_type in ASSET_TYPES:
        guidance = asset_type_guidance(asset_type)
        lines.append(
            "| {name} | {rw}x{rh} | {ratio} | {minw}x{minh} | {maxw}x{maxh} | {mb} MB | {formats} | {alpha} |".format(
                name=asset_type.replace("_", " ").title(),
                rw=guidance["recommended_width"],
                rh=guidance["recommended_height"],
                ratio=guidance["aspect_ratio"],
                minw=guidance["minimum_width"],
                minh=guidance["minimum_height"],
                maxw=guidance["maximum_width"],
                maxh=guidance["maximum_height"],
                mb=guidance["maximum_bytes"] // 1_000_000,
                formats=", ".join(guidance["formats"]),
                alpha=guidance["transparency"],
            )
        )
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    OUTPUT.write_text(document(), encoding="utf-8")
    print(OUTPUT)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
